server:
  port: 8081

appDescription: "Plazoleta"
appVersion: "1.0.0"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plazoleta
    username: postgres
    password: postgres


usuario:
  url: "http://localhost:8080/usuario"

app:
  jwt:
    llave: "8979d62702cf56721c86967eff5b1cb820982de3b45f40f9c12f5762cde6f419"